### ISSUE TITLE
server.js fails on WebStorm 12 EAP with node version 3.8.0

### ISSUE THREAD

**Issue by biospring** [vaadin/expense-manager-demo#13]
HoonsMBPRetina:server hoonchung$ npm --version
3.8.0
HoonsMBPRetina:server hoonchung$ pwd
/Users/hoonchung/Documents/WebstormProjects/PolymerJSProjects/vaadin-expense-manager-demo-master/server
HoonsMBPRetina:server hoonchung$ node server.js
/Users/hoonchung/Documents/WebstormProjects/PolymerJSProjects/vaadin-expense-manager-demo-master/server/server.js:2
(() => {
  ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:69:16)
    at Module._compile (module.js:432:25)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Function.Module.runMain (module.js:490:10)
    at startup (node.js:124:16)
    at node.js:807:3
HoonsMBPRetina:server hoonchung$

**Comment by marcushellberg** [comment]
The demo requires a more recent Node version (4+ should work, 5 is what I'm running).

**Comment by biospring** [comment]
Thanks. Upgrading to 5.7.0 solved it.
